package Exception

fun main(){
    var num = 10 / 0 //throws exception
    println(num)
}